[project]
name = "jupyterlab-uv-custom"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
  "jupyter-core",
  "jupyterlab",
  "nbclassic",
  "notebook>=7.2.2",
  "ipython",
  "ipykernel",
  "ipympl",
  "ipywidgets",
  "matplotlib",  
  "widgetsnbextension",

  "altair",
  "bokeh",
  "bottleneck",
  "cloudpickle",
  "cython",
  "dask",
  "dill",
  "h5py",
  "numexpr",
  "openpyxl",
  "patsy",
  "protobuf",
  "tables",
  "sympy",
  "xlrd",

  "scipy",
  "scikit-image",
  "scikit-learn",
  "statsmodels",
  "dotenv",
  "seaborn",
  "sqlalchemy",
  "polars",
  "httpx",
  "beautifulsoup4",
  "numba",

  "jupyterlab_lsp",
  "python-lsp-server[all]",
  "jupyterlab-git",
  # todo: get ty to work with lsp plugin
  #"ruff",
  #"ty"
]


#[tool.ty.rules]
# unused-ignore-comment = "warn"
# redundant-cast = "ignore"
# possibly-missing-attribute = "error"
# possibly-missing-import = "error"
