## -*- containerfile-image-name: "jupyterlab-uv-custom" -*-

# Modified from the official jupyter dockerfile (datascience-notebook iirc) to
# use uv and to use a unix socket (better access control on shared servers) If
# running this on a remote shared server, SSH tunnel it to a port on your
# localhost: `ssh -L 8888:/path/to/socket.sock user@server` Note: You will need
# to manually `podman unshare chmod 660 sockets/socket.sock` the socket, and
# there's some setup. For more info see the README.md

# Plan is to rewrite this from scratch to be podman (OCI) compatible, using the
# docker-stacks as a reference. I'll of course keep a note thanking them.

# Original is Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

FROM ubuntu:24.04
COPY --from=ghcr.io/astral-sh/uv:0.9.15 /uv /uvx /bin/

LABEL maintainer="Chrstfer <chrstfer@users.noreply.github.com>"

# my project uses 3.12 but set it to what you need; jupyter supports from 3.7 as of Jan 2026 according to google
ARG PYTHON_VERSION=3.12
ARG CONTAINER_INCLUDES="./container-includes"

ARG NB_USER="jluv"
ARG NB_UID="1000"
ARG NB_GID="100"

USER root

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes
RUN apt-get upgrade --yes
RUN apt-get install --yes --no-install-recommends \
    # from foundation
    bzip2 \
    ca-certificates \
    locales \
    netbase \
    sudo \
    tini \
    wget \
    # from base-notebook
    fonts-liberation \
    pandoc \
    run-one \
    # from minimal-notebook
    curl \
    git \
    nano-tiny \
    tzdata \
    unzip \
#    vim-tiny \
    openssh-client \
    less \
    texlive-xetex \
    texlive-fonts-recommended \
    texlive-plain-generic \
    xclip \
    # from scipy and datascience
    fonts-dejavu \
    gfortran \
    gcc \
    # for cython: https://cython.readthedocs.io/en/latest/src/quickstart/install.html
    build-essential \
    # for latex labels
    cm-super \
    dvipng \
    # for matplotlib anim
    ffmpeg \
    # for jupyter plugins
    nodejs
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Create alternative for nano -> nano-tiny
RUN update-alternatives --install /usr/bin/nano nano /bin/nano-tiny 10
# Set locale and default bash settings
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    echo "C.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen
# enable colors for all users
RUN sed -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' /etc/skel/.bashrc

# in case the user changes NB_UID to something that exists
RUN if grep -q "${NB_UID}" /etc/passwd; then \
        userdel --remove $(id -un "${NB_UID}"); \
    fi

# fix-permissions script from jupyter official images
COPY ${CONTAINER_INCLUDES}/fix-permissions /usr/local/bin/fix-permissions
RUN chmod a+rx /usr/local/bin/fix-permissions
# Create "${NB_USER}" user (`jluv` by default) with UID="${NB_UID}" (`1000` by
# default) and in the 'users' group and make sure these dirs are writable by the
# `users` group.
RUN echo "auth requisite pam_deny.so" >> /etc/pam.d/su && \
    sed -i.bak -e 's/^%admin/#%admin/' /etc/sudoers && \
    sed -i.bak -e 's/^%sudo/#%sudo/' /etc/sudoers && \
    useradd --no-log-init --create-home --shell /bin/bash --uid "${NB_UID}" --no-user-group "${NB_USER}" && \
    chmod g+w /etc/passwd && \
    rm -rf "/home/${NB_USER}/.cache/" && \
    fix-permissions "/home/${NB_USER}"

#### TODO: Split to multistage here?

# General, uv, and jupyter env vars
ENV SHELL=/bin/bash \
    NB_USER="${NB_USER}" \
    NB_UID="${NB_UID}" \
    NB_GID="${NB_GID}" \
    LC_ALL=C.UTF-8 \
    LANG=C.UTF-8 \
    LANGUAGE=C.UTF-8 \
    PATH="/home/${NB_USER}/.local/bin:${PATH}" \
    HOME="/home/${NB_USER}" \
    UV_TOOL_BIN_DIR=/home/${NB_USER}/.uv_tools \
    JP_SOCK=/home/${NB_USER}/.sockets/jupyterlab-server.sock

# Dropping support for hooks
# RUN mkdir /usr/local/bin/start-notebook.d && mkdir /usr/local/bin/before-notebooks.d

# switch to user joyvan and create some dirs
USER ${NB_UID}
WORKDIR /home/${NB_USER}

# uv File Includes (needed before sync)
COPY --chown=${NB_UID}:${NB_GID} ${CONTAINER_INCLUDES}/pyproject.toml /home/${NB_USER}/
# Sync uv before doing the Jupyter stuff
RUN printf "%s\n" "${PYTHON_VERSION}" > /home/${NB_USER}/.python-version && uv sync
# Run jupyter setup
RUN uv run jupyter server --generate-config && uv run jupyter lab clean
# Import matplotlib the first time to build the font cache
RUN MPLBACKEND=Agg uv run python -c "import matplotlib.pyplot"
# Add kernel
RUN uv run --python 3.12 -m ipykernel install --user --name uvkernel --display-name "Python (uv 3.12 kernel)"
RUN ls -la /home/${NB_USER}/.cache
RUN mkdir work notebooks .sockets
# Jupyter config adds as late as possible to avoid cache busting
COPY --chown=${NB_UID}:${NB_GID} ${CONTAINER_INCLUDES}/.jupyter/jupyter_server_config.py /home/${NB_USER}/.jupyter/jupyter_server_config.py
COPY --chown=${NB_UID}:${NB_GID} ${CONTAINER_INCLUDES}/.jupyter/jupyter_server_config.d /home/${NB_USER}/.jupyter/jupyter_server_config.d/
#General File Includes as late as possible to avoid cache busting
COPY --chown=${NB_UID}:${NB_GID} ${CONTAINER_INCLUDES}/.config /home/${NB_USER}/.config
COPY --chown=${NB_UID}:${NB_GID} ${CONTAINER_INCLUDES}/.env.local /home/${NB_USER}/.env.local
RUN fix-permissions "/home/${NB_USER}"

# Copy /usr/local/bin files as late as possible to avoid cache busting
COPY ${CONTAINER_INCLUDES}/usr.local.bin/* /usr/local/bin/

# Set the port stuff (TODO: make this an option)
# ENV JUPYTER_PORT=8888
# EXPOSE $JUPYTER_PORT

# Configure container entrypoint
ENTRYPOINT ["tini", "-g", "--", "/usr/local/bin/start.sh"]
CMD uv run --python 3.12 jupyter lab --no-browser --sock "${JP_SOCK}" --IdentityProvider.token='pw !2345'

# TODO: Multistage, remove uv after syncing project necessities, clean up
# Add Project
# TODO: add some variables for project name, python version, etc, then a RUN that creates a project kernel; then we can cut down the main uv requirements
# ADD --chown=${NB_UID}:${NB_GID} project ${HOME}/project
