* Jupyterlab with uv
This repo contains a customized Containerfile for Jupyterlab that uses uv for
package management. It's a work in progress at the moment but it works for me
(YMMV).

This isn't quite an unopinionated, blank-slate Jupyterlab setup. I've included
what I like in terms of default configuration and plugins, such as language
server support with pylsp. The official docker images are perfectly serviceable,
if you don't like this setup.

The example notebook uses polars. Its just better than pandas, I stand by that
and I want others to know.

** Features:
- Uses uv for package management for speed improvements and because uv is awesome
- Jupyter server defaults to using a unix socket, because I run my Jupyter on a
  /shared/ server that I SSH into (so only listening on localhost still exposes
  Jupyter to other users, a security issue).
- Scripts that add workarounds for podman rootless environments.
- Some default plugins and associated config:
  - Jupyter-lsp with pylsp
  - pympl and pywidgets for matplotlib widgets
- A shared folder (~/notebooks in the container) for saving notebooks to the
  host (I needed a shared folder for the socket too, might as well add this one)
    
** Container Architecture
*** Base Image: ubuntu:24.04
*** Package Manager: uv (Rust-based)
*** Key Benefits
- uv over conda
  - 10-100x Faster resolution than Conda
  - Reduced image footprint
  - Deterministic builds via uv.lock

** TODO To-Do:
- [X] Rewrite the Containerfile from scratch, pulling what needs to be pulled in
  from the Jupyter docker-stacks repo. I don't want to call it bloated, it
  just has more than I need and isn't fully OCI compliant (uses "SHELL"
  instruction).
- [-] Switch entirely over to uv. Currently there is still conda reliance and it
  loads a conda venv by default (I'd rather it use uv)
- [X] change the username
- [-] ARG variables to control build and run
- [X] Manage install of jupyter/dependencies with uv
- [ ] Get R setup (right now ive ignored basically everything involving it) 
  - [ ] same with julia? 
- [ ] Setup Multistage build, separating ubuntu package install from general setup?
  - [ ] Generally optimize Containerfile while we're at it, for size and speed of build
- [ ] Remove/switch label references from "docker" to something more standards oriented (ie "container")
- [ ] Deep dive into this permissions issue and cache issue.
- [ ] Update to python 3.14 if possible with needed packages (cull back list)
- [ ] Create a hardened final image taking this image as a prior stage setting
  up the environment but removing as much as possible to reduce dependencies,
  image size, and attack surface.
- [ ] Benchmark against official jupyter images with conda
*** plugins to look into
- https://github.com/leotaku/jupyter-ruff
- 
* Benchmark
** Official Jupyter image: 
* Thanks
A lot of this is based on Jupyter's docker-stacks. Original version uses
minimal-notebook as a base image, and is based on a stripped down version of the
scipy and datascience notebooks that i converted to use uv. However, as I use
podman and wanted to make this purely OCI compatible, I went through the stack
of images beneath that and converted this container to use what was needed
throughout the stack (while avoiding the use of SHELL). This version doesnt rely
on conda, using uv to manage what would be called the "base" venv with a
pyproject.toml in the users home directory. Is this good practice? I have no
idea, time will tell.

If I've incorrectly applied the licensing or copyright, please open an issue or
contact me.
